targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|op_builder:
        enabled: true
        options:
          schema: gql_example_flutter|lib/schema.graphql
      gql_build|fragment_builder:
        enabled: true
        options:
          schema: gql_example_flutter|lib/schema.graphql
      gql_build|data_builder:
        enabled: true
        options:
          schema: gql_example_flutter|lib/schema.graphql
      gql_build|req_builder:
        enabled: true
        options:
          schema: gql_example_flutter|lib/schema.graphql
